/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Triforce.intrefaces;

import java.awt.Color;
import javax.swing.JOptionPane;
import br.com.Triforce.model.FornecedorRegistro;

/**
 *
 * @author a145292
 */
public class Cadastrar_Fornecedor extends Geral {

    /**
     * Creates new form CadastroFornecedor
     */
    private FornecedorRegistro forReg;
    
    public Cadastrar_Fornecedor(FornecedorRegistro forReg) {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_cod.setText(Integer.toString(forReg.retornaMap()+1));
        txt_cod.setEditable(false);
        this.forReg = forReg;
        
        lbl_confirmarRazaosocial.setVisible(false);
        lbl_confirmarRazaosocial.setForeground(Color.red);
        lbl_confirmarNomeFantasia.setVisible(false);
        lbl_confirmarNomeFantasia.setForeground(Color.red);
        lbl_confirmarCnpj.setVisible(false);
        lbl_confirmarCnpj.setForeground(Color.red);
        lbl_confirmarTelefone.setVisible(false);
        lbl_confirmarTelefone.setForeground(Color.red);
        lbl_confirmarEmail.setVisible(false);
        lbl_confirmarEmail.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastrofornecedor = new javax.swing.JLabel();
        lbl_razaosocial = new javax.swing.JLabel();
        lbl_nomefantasia = new javax.swing.JLabel();
        lbl_cnpj = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        txt_razaosocial = new javax.swing.JTextField();
        txt_nomefantasia = new javax.swing.JTextField();
        txt_cnpj = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        btn_gravar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        lbl_confirmarRazaosocial = new javax.swing.JLabel();
        lbl_confirmarCnpj = new javax.swing.JLabel();
        lbl_confirmarNomeFantasia = new javax.swing.JLabel();
        lbl_confirmarTelefone = new javax.swing.JLabel();
        lbl_confirmarEmail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        lbl_cod = new javax.swing.JLabel();

        setTitle("Cadastrar Fornecedor");
        setMinimumSize(new java.awt.Dimension(380, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cadastrofornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cadastrofornecedor.setText("Cadastro Fornecedor");
        getContentPane().add(lbl_cadastrofornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_razaosocial.setText("Razão social*");
        getContentPane().add(lbl_razaosocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_nomefantasia.setText("Nome fantasia*");
        getContentPane().add(lbl_nomefantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lbl_cnpj.setText("CNPJ*");
        getContentPane().add(lbl_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lbl_email.setText("Email*");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lbl_telefone.setText("Telefone*");
        getContentPane().add(lbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        getContentPane().add(txt_razaosocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, -1));
        getContentPane().add(txt_nomefantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 330, -1));
        getContentPane().add(txt_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 330, -1));
        getContentPane().add(txt_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, -1));

        btn_gravar.setText("Gravar");
        btn_gravar.setActionCommand("Salvar");
        btn_gravar.setMaximumSize(new java.awt.Dimension(80, 30));
        btn_gravar.setMinimumSize(new java.awt.Dimension(80, 30));
        btn_gravar.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        btn_voltar.setText("Voltar");
        btn_voltar.setMaximumSize(new java.awt.Dimension(80, 30));
        btn_voltar.setMinimumSize(new java.awt.Dimension(80, 30));
        btn_voltar.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        lbl_confirmarRazaosocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmarRazaosocial.setText(" *");
        getContentPane().add(lbl_confirmarRazaosocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 22, -1));

        lbl_confirmarCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmarCnpj.setText(" *");
        getContentPane().add(lbl_confirmarCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 22, -1));

        lbl_confirmarNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmarNomeFantasia.setText(" *");
        getContentPane().add(lbl_confirmarNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 22, -1));

        lbl_confirmarTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmarTelefone.setText(" *");
        getContentPane().add(lbl_confirmarTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 22, -1));

        lbl_confirmarEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmarEmail.setText(" *");
        getContentPane().add(lbl_confirmarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 22, -1));

        jLabel7.setText("* campos obrigátorios");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));
        getContentPane().add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, -1));

        lbl_cod.setText("Codigo");
        getContentPane().add(lbl_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        // TODO add your handling code here:
        if(txt_razaosocial.getText().length() > 0 ){
            lbl_confirmarRazaosocial.setVisible(false);
        }else 
        {
            lbl_confirmarRazaosocial.setVisible(true);
        }
        if(txt_nomefantasia.getText().length() > 0 )
        {
            lbl_confirmarNomeFantasia.setVisible(false);
        }else
        {
            lbl_confirmarNomeFantasia.setVisible(true);
        }
        if(txt_cnpj.getText().length() > 0){
            lbl_confirmarCnpj.setVisible(false);
        }else 
        {
            lbl_confirmarCnpj.setVisible(true);
        }
        if (txt_telefone.getText().length() > 0 )
        {
            lbl_confirmarTelefone.setVisible(false);
        }else{
            lbl_confirmarTelefone.setVisible(true);
        }
        if(txt_email.getText().length() > 0 )
        {
            lbl_confirmarEmail.setVisible(false);
        }else
        {
            lbl_confirmarEmail.setVisible(true);
        }
         if(txt_razaosocial.getText().length() > 0 
                 &&txt_nomefantasia.getText().length() > 0 
                 &&txt_cnpj.getText().length() > 0 
                 &&txt_telefone.getText().length() > 0
                 &&txt_email.getText().length() > 0){
             
             forReg.adicionaFornecedor(forReg.retornaMap()+1,
                                       txt_razaosocial.getText(),
                                       txt_nomefantasia.getText(), 
                                       txt_cnpj.getText(),
                                       txt_telefone.getText(), 
                                       txt_email.getText());
             
             JOptionPane.showMessageDialog(null, "Dados Cadastrados com sucesso");
             limptaTuto();
         }else 
         {
             JOptionPane.showMessageDialog(null, "Favor inserir dados nos campos obrigatórios" );
         }
    }//GEN-LAST:event_btn_gravarActionPerformed

    public void limptaTuto() {
        txt_razaosocial.setText("");
        txt_telefone.setText("");
        txt_email.setText("");
        txt_cod.setText(Integer.toString(forReg.retornaMap() + 1));
        txt_nomefantasia.setText("");
        txt_cnpj.setText("");
        
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_cadastrofornecedor;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_cod;
    private javax.swing.JLabel lbl_confirmarCnpj;
    private javax.swing.JLabel lbl_confirmarEmail;
    private javax.swing.JLabel lbl_confirmarNomeFantasia;
    private javax.swing.JLabel lbl_confirmarRazaosocial;
    private javax.swing.JLabel lbl_confirmarTelefone;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nomefantasia;
    private javax.swing.JLabel lbl_razaosocial;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_cnpj;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nomefantasia;
    private javax.swing.JTextField txt_razaosocial;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
