/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Triforce.intrefaces;

import br.com.Triforce.model.ClienteRegistro;
import br.com.Triforce.model.ProdutoEstoque;

/**
 *
 * @author a145292
 */
public class Efetuar_Venda extends Geral{

    /**
     * Creates new form EfetuarVenda
     */
    private ProdutoEstoque prod;
    private ClienteRegistro cli;
    public Efetuar_Venda(ProdutoEstoque prod,ClienteRegistro cli) {
        initComponents();
        this.prod = prod;
        this.cli=cli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_efetuarvenda = new javax.swing.JLabel();
        btn_remover = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_venda = new javax.swing.JTable();
        btn_consultarcliente = new javax.swing.JButton();
        lbl_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        txt_cliente = new javax.swing.JTextField();
        lbl_cliente = new javax.swing.JLabel();
        lbl_totalpagar = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();

        setTitle("Vendas");

        lbl_efetuarvenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_efetuarvenda.setText("Efetuar Venda");

        btn_remover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_remover.setText("Remover");

        btn_adicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_adicionar.setText("Adicionar");
        btn_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adicionarMouseClicked(evt);
            }
        });

        tab_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Valor", "Quantidade", "Autor", "Categoria", "Volume", "DtaLco"
            }
        ));
        jScrollPane1.setViewportView(tab_venda);

        btn_consultarcliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_consultarcliente.setText("Consultar Cliente");
        btn_consultarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarclienteMouseClicked(evt);
            }
        });

        lbl_produto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_produto.setText("Produto:");

        lbl_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cliente.setText("Cliente:");

        lbl_totalpagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_totalpagar.setText("Total a ser pago:");

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_totalpagar)
                    .addComponent(lbl_efetuarvenda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_produto)
                            .addComponent(lbl_cliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txt_produto))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_remover))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_consultarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_adicionar, btn_remover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_efetuarvenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consultarcliente)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cliente)
                    .addComponent(btn_voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionar)
                    .addComponent(btn_remover)
                    .addComponent(lbl_produto)
                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_totalpagar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_consultarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarclienteMouseClicked
        abreJanela(new Consultar_Cliente(cli), 0);
    }//GEN-LAST:event_btn_consultarclienteMouseClicked

    private void btn_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionarMouseClicked
        abreJanela(new Consultar_Produto(prod), 0);
    }//GEN-LAST:event_btn_adicionarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_consultarcliente;
    private javax.swing.JButton btn_remover;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_efetuarvenda;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JLabel lbl_totalpagar;
    private javax.swing.JTable tab_venda;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_produto;
    // End of variables declaration//GEN-END:variables
}
