/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Triforce.intrefaces;

import br.com.Triforce.model.ClienteRegistro;
import br.com.Triforce.model.CodigoExcluidoRegistro;
import br.com.Triforce.model.FornecedorRegistro;
import br.com.Triforce.model.FuncionarioRegistro;
import br.com.Triforce.model.PedidoRegistro;
import br.com.Triforce.model.ProdutoEstoque;

/**
 *
 * @author angelo
 */
public class Login extends javax.swing.JFrame {

   
    /**
     * Creates new form Login
     */
      private ProdutoEstoque prod;
      private FornecedorRegistro forReg;
      private FuncionarioRegistro funReg;
      private ClienteRegistro cliReg;
      private PedidoRegistro reg;
       private CodigoExcluidoRegistro ex;
    public Login(ProdutoEstoque prod,FornecedorRegistro forReg,FuncionarioRegistro funReg,ClienteRegistro cliReg,PedidoRegistro reg,CodigoExcluidoRegistro ex) {
        initComponents();
        
         this.prod = prod;
         this.forReg = forReg;
         this.funReg = funReg;
         this.cliReg = cliReg;
         this.reg = reg ;
         this.ex = ex;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_User = new javax.swing.JLabel();
        lbl_Senha = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        psd_Senha = new javax.swing.JPasswordField();
        lbl_Titulo = new javax.swing.JLabel();
        btn_Entrar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(350, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_User.setText("Usuário:");
        getContentPane().add(lbl_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lbl_Senha.setText("Senha:");
        getContentPane().add(lbl_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 162, -1));

        psd_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psd_SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(psd_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 162, -1));

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_Titulo.setText("Triforce");
        getContentPane().add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        btn_Entrar.setText("Entrar");
        btn_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EntrarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        btn_Sair.setText("Sair");
        btn_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SairMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Triforce/icones/divided-by-cipher.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserActionPerformed

    private void psd_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psd_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psd_SenhaActionPerformed

    private void btn_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EntrarMouseClicked
        this.dispose();
        new Principal(prod,forReg,funReg,cliReg,reg,ex).setVisible(true);
    }//GEN-LAST:event_btn_EntrarMouseClicked

    private void btn_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_SairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        final ProdutoEstoque a = new ProdutoEstoque();
        final FornecedorRegistro b = new FornecedorRegistro();
        final FuncionarioRegistro c = new FuncionarioRegistro();
        final ClienteRegistro d = new ClienteRegistro();
        final PedidoRegistro e = new PedidoRegistro();
        final CodigoExcluidoRegistro f = new CodigoExcluidoRegistro();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(a,b,c,d,e,f).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPasswordField psd_Senha;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
